export default {
  errorState: false,
  scrollDisabled: false,
  drawerOpen: false,
  scrollY: 0,
  shareDialogOpen: false,
  shareDialogUrl: null,
  restoreDialogOpen: false,
  registerDialogOpen: false,
  loginDialogOpen: false,
  logoutDialogOpen: false,
  backupDialogOpen: false,
  qrDialogOpen: false,
  qrWallet: null,
  sendDialogOpen: false,
  thumbnailDialogOpen: false,
  thumbnailDialogCover: null,
  thumbnailDialogVideo: null,
};
